language: python
python:
  - "2.7"
  - "3.4"
script: python setup.py install && nosetests test/ && tox
branches:
  only:
    - master
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu precise-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y liberasurecode-dev libffi-dev python-setuptools
  - sudo easy_install pip
  - pip install tox
