#!/usr/bin/python3

from pyeclib.ec_iface import ECDriver

input = b'test'

ec = ECDriver(k=2, m=1, ec_type='liberasurecode_rs_vand')
fragments = ec.encode(input)
assert ec.decode(fragments[0:2]) == input

